### ISSUE TITLE
Fix usage of path, replace with filepath

### ISSUE THREAD

**Issue by jahkeup** [aws/ec2-macos-init#23]
File paths are being joined by the `path` package in some cases and should instead be using `filepath`.

https://github.com/aws/ec2-macos-init/blob/f465f4794d23505f39edf1cfa5bb21495438e04b/lib/ec2macosinit/instancehistory.go#L8

This shouldn't be an issue for this codebase as its intended to run on a platform (macOS) that uses `/` as its separator, so this is more of a "code smell" bug fix issue.

**Comment by SamMHD** [comment]
@jahkeup, any review?
