### ISSUE TITLE
brew is missing after imaging

### ISSUE THREAD

**Issue by tyen-brex** [aws/ec2-macos-init#27]
Created a custom image from the ARM macOS monterey 12.6.1 image. After creating a new instance the `brew` utility is no longer present

```
sh-3.2$ ls -la /usr/local/bin
total 0
drwxr-xr-x  3 root  wheel   96 Nov  2 00:20 .
drwxr-xr-x  5 root  wheel  160 Nov  2 00:20 ..
lrwxr-xr-x  1 root  wheel   33 Nov  2 00:20 ec2-macos-init -> /usr/local/libexec/ec2-macos-init
```

**Comment by okudajun** [comment]
Hello @tyen-brex,

Homebrew chose the default installation path as `/opt/homebrew` when they started supporting macOS for Apple Silicon, and AWS's macOS ARM64 AMIs also use the path. Please find `brew` command under `/opt/homebrew`.

**Comment by tyen-brex** [comment]
Thanks! I missed it
