### ISSUE TITLE
Failed Module Run Doesn't Log Message

### ISSUE THREAD

**Issue by awstimvan** [aws/ec2-macos-init#5]
Hi, I'm trying to write a userdata script to install some software at launch. It's failing somewhere, but I don't know why. The problem is that when the userdata module (or any other module) fails (`err != nil`), the resulting log line only logs `err`, but not `message`:

https://github.com/aws/ec2-macos-init/blob/master/run.go#L115

In the case of the userdata module, the `message` variable would contain the contents of `stdout` and `stderr`, which would almost certainly help me debug my issue. As is, that information is gone when I go to log in and debug the problem, so I'm left guessing.

The irony is that it does log `message` when the script succeeds, exactly when I don't need it. :)

**Comment by mattcataws** [comment]
Hey, thanks for opening an issue to track this. We're working on a fix for this that will be included in a future update. Please let us know if any new data comes up regarding this issue.

**Comment by mattcataws** [comment]
This should now be fixed with the commit [33705b7](https://github.com/aws/ec2-macos-init/commit/33705b7c2bb66c87402945f93e3c81a434eb7572). I'm going to close this issue but please include any more information and reopen it if the problem persists.
